env:
  maze_size: 3
  num_arms: 3
  num_maze: -1
  max_episode_steps: 256
  target_reward: 1.0
  per_step_reward: 0.0
  num_labels: 16
  render_mode: null
  no_duplication: True
  seed: 10
  maps: null
  n_envs: 128
  epn: True
  norm_reward: True
  norm_obs: False

ppo:
  batch_size: 128
  n_steps: 128
  n_epochs: 5
  gamma: 0.95
  gae_lambda: 0.95
  max_grad_norm: 1.0
  ent_coef: 0.001
  normalize_advantage: True
  verbose: 1

epn:
  embedding_size: 16
  num_heads: 1
  hidden_size: 64
  num_iterations: 4

optim:
  total_timesteps: 500_000_000
  linear_schedule: True
  learning_rate: 0.0001
  clip_range: 0.2

logger:
  upload_to_wandb: False
  run_dir: 
  proj_name: radial_arm_maze
  group_name: EPN

seed: 10
